### ISSUE TITLE
Create example showing filter/highlight with Query data

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/safety-shift-plot#12]

**Comment by samussiah** [comment]
As queries are field-level I'm going to assume we're limiting queries to `settings.value_col`, i.e. the results themselves.  In this scenario we'd only need an additional query flag column.

**Comment by samussiah** [comment]
Actually I don't think there's anything to be done here.  The plotted values are aggregates: mean, min or max.  What do you think @jwildfire ?  Are to highlight an aggregate with an queried input observation?

**Comment by jwildfire** [comment]
Yeah, this is definitely a bit messy for this one. I guess we could add a filter on the raw data that removes queried values ... Anything else would require a major refactor of the graphic. Let's run this by Karen and see what she wants. I think it's fine to bump it to v1.3 if needed.

**Comment by jwildfire** [comment]
Going with filter only (no highlight) for v1.3.0. Can create separate issue for highlighting in a future release if needed.
