### ISSUE TITLE
Add Ability to Mouseover Labels for Visits

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/safety-shift-plot#2]
Be able to mouseover labels for a list of visits at baseline/end of study

**Comment by jwildfire** [comment]
Might be ok as is since the visits are shown in the controls.

**Comment by jwildfire** [comment]
Easy to do, so including in 1.2

**Comment by samussiah** [comment]
Does the `possible-visits` text just underneath the controls take care of this?  See [this gist](http://bl.ocks.org/samussiah/raw/2f9e106a5cccff3c964b87b62bc03d42/).

**Comment by jwildfire** [comment]
I think the issue is that it's a little hard to tell what is selected in the "baseline" and "comparison" multi-selects in the controls. Idea is to add a mouseover via a`<title>` on the `.axis .labels`. Sound doable?

**Comment by samussiah** [comment]
Yup, thanks for the clarification.
