### ISSUE TITLE
safety-shift-plot not drawing where expected in webcharts v1.10.0

### ISSUE THREAD

**Issue by dschwentker** [RhoInc/safety-shift-plot#50]
safety-shift-plot loads using Webcharts v1.10.0-dev, but the drawing is off when I try to select several points in the charts. When I click with my mouse and drag it, I expect it to draw a box in the are where I clicked and dragged, but it draws the box beginning in the top left corner of the chart every time.

Also, once drawn, I cannot click out of the box to get the drawn box to disappear and show the chart with no box without re-rendering the whole chart.

**Comment by samussiah** [comment]
Fixed in webcharts.
